// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: proto/transaction/transaction.proto

package transaction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransactionManagementClient is the client API for TransactionManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionManagementClient interface {
	UpTransaction(ctx context.Context, in *UpdateTxRequest, opts ...grpc.CallOption) (*UpdateTxResponse, error)
	DownTransaction(ctx context.Context, in *UpdateTxRequest, opts ...grpc.CallOption) (*UpdateTxResponse, error)
}

type transactionManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionManagementClient(cc grpc.ClientConnInterface) TransactionManagementClient {
	return &transactionManagementClient{cc}
}

func (c *transactionManagementClient) UpTransaction(ctx context.Context, in *UpdateTxRequest, opts ...grpc.CallOption) (*UpdateTxResponse, error) {
	out := new(UpdateTxResponse)
	err := c.cc.Invoke(ctx, "/transaction.TransactionManagement/UpTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionManagementClient) DownTransaction(ctx context.Context, in *UpdateTxRequest, opts ...grpc.CallOption) (*UpdateTxResponse, error) {
	out := new(UpdateTxResponse)
	err := c.cc.Invoke(ctx, "/transaction.TransactionManagement/DownTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionManagementServer is the server API for TransactionManagement service.
// All implementations must embed UnimplementedTransactionManagementServer
// for forward compatibility
type TransactionManagementServer interface {
	UpTransaction(context.Context, *UpdateTxRequest) (*UpdateTxResponse, error)
	DownTransaction(context.Context, *UpdateTxRequest) (*UpdateTxResponse, error)
	mustEmbedUnimplementedTransactionManagementServer()
}

// UnimplementedTransactionManagementServer must be embedded to have forward compatible implementations.
type UnimplementedTransactionManagementServer struct {
}

func (UnimplementedTransactionManagementServer) UpTransaction(context.Context, *UpdateTxRequest) (*UpdateTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpTransaction not implemented")
}
func (UnimplementedTransactionManagementServer) DownTransaction(context.Context, *UpdateTxRequest) (*UpdateTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownTransaction not implemented")
}
func (UnimplementedTransactionManagementServer) mustEmbedUnimplementedTransactionManagementServer() {}

// UnsafeTransactionManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionManagementServer will
// result in compilation errors.
type UnsafeTransactionManagementServer interface {
	mustEmbedUnimplementedTransactionManagementServer()
}

func RegisterTransactionManagementServer(s grpc.ServiceRegistrar, srv TransactionManagementServer) {
	s.RegisterService(&TransactionManagement_ServiceDesc, srv)
}

func _TransactionManagement_UpTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionManagementServer).UpTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.TransactionManagement/UpTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionManagementServer).UpTransaction(ctx, req.(*UpdateTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionManagement_DownTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionManagementServer).DownTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.TransactionManagement/DownTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionManagementServer).DownTransaction(ctx, req.(*UpdateTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionManagement_ServiceDesc is the grpc.ServiceDesc for TransactionManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.TransactionManagement",
	HandlerType: (*TransactionManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpTransaction",
			Handler:    _TransactionManagement_UpTransaction_Handler,
		},
		{
			MethodName: "DownTransaction",
			Handler:    _TransactionManagement_DownTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transaction/transaction.proto",
}
